### PR TITLE
Add Support List Customers.

### PR DESCRIPTION
**Pull request by pocket7878**
Implement `Customer::list` method.

Maybe we can implement list method in the same way.

### CODE REVIEW

**Comment by kestred** [comment]
Thanks!  I like how you implemented the `RangeQuery` (it seems to match similarly to the official Go/Python libraries which I use as a benchmark-- and also utilizes Serde well).

---------------------

There are a couple changes I'd like in the pull request:

1. Please update (or rebase) your branch to include only changes **related to the feature** being added and remove any unrelated **formatting changes**.
    (I've updated master with a `.rustfmt.toml` config file and applied `cargo fmt` in a commit; hopefully this satiates your editor.)

2. I prefer to implement requests in the same way they are sent in the `curl` examples in the API documentation.   For `GET` requests, query params are sent in the URL instead of the body, so we shouldn't need to use `get_with_params` e.g.

```rust
    pub fn list(client: &Client, params: InvoiceListParams) -> Result<List<Invoice>, Error> {
        client.get(&format!("/invoices?{}", qs::to_string(&params)?))
    }
```

**Comment by pocket7878** [comment]
@kestred Thank you for your review. I'll try to fix commits.

**Comment by pocket7878** [comment]
@kestred 
I have fixed commits 😄

**Comment by kestred** [comment]
I've implemented some changes to the `RangeQuery` so that both an upper and lower bound could be provided in a single query (eg.  `created[gt]=1&created[lt]=y`).

The changes have been published on [crates.io](https://crates.io/) as part of the `0.4.1` release.

**Pull request merged**
